import { Button } from "@/components/ui/button"
import {
  Card,
  CardContent,
  CardDescription,
  CardFooter,
  CardHeader,
  CardTitle,
} from "@/components/ui/card"
import { Doc } from "@/convex/_generated/dataModel"
import { Eye, Loader2 } from "lucide-react"
import Link from "next/link"

// Doc is a type that is generated by Convex based on the schema of the documents table
export function DocumentCard({ document }: { document: Doc<"documents"> }) {
  return (
    <Card>
      <CardHeader>
        <CardTitle>{document.title}</CardTitle>
        {/* <CardDescription>Document description</CardDescription> */}
      </CardHeader>
      <CardContent>
        {/* TODO: update card content */}
        <div>{!document.description ? (
          <div className="flex justify-center">
          <Loader2 className="animate-spin" />
          </div>
        ) : (
          document.description
        )}</div>
      </CardContent>
      <CardFooter>
        <Button asChild variant="secondary">
          <Link href={`/documents/${document._id}`}>
            <Eye className="w-4 h-4 mr-2" />
            View
          </Link>
        </Button>
      </CardFooter>
    </Card>
  )
}